### ISSUE TITLE
No need in getattr

### ISSUE THREAD

**Issue by kuzmoyev** [msulaim/API-and-REST#3]
Hello. I'm a developer of gcsa. I've come across your repo and noticed that you are using it in a bit unusual way. For example:

https://github.com/msulaim/API-and-REST/blob/a11d86caec0628b2afd40959738dad50809e6354/Google%20Calendar%20Event%20Categorizer/categorizer.py#L206

Do you know that `getattr(event, "summary")`  is exactly equivalent to `event.summary`? Same goes for `event.start`, `event.end`, etc.

I'm trying to make it easier and more understandable to use. Do you think I could update somehow the docs to make it more clear?

**Comment by msulaim** [comment]
Consider me a beginner but you are right, thanks ! I found gcsa incredibly easy to use, it is well documented and the example you gave is very helpful. These are the obstacles I faced:

- I had to work my way around authenticating multiple Google Calendars, it turns out that a tab opens in the browser if you create a new token, so maybe an example that shows authentication of multiple Google Calendars would be helpful
- I had to use `dir` to figure out the methods and attributes of the Event object, I found them later on "Read the docs"
- I had to calculate "Duration", having a duration attribute could be helpful

I hope this helps, great job on gcsa !

**Comment by kuzmoyev** [comment]
Thank you for the feedback. I will think how to make it easier for a developer
